#!/usr/bin/env python3
"""Import card illustrations: python3 scripts/import-art.py <folder of PNGs named by art file, e.g. sl-8.png, modern-satellite-2.png>

Writes assets/art/cards/<file>.webp (card art window), assets/art/cards/sm/<file>.webp (gallery tiles)
and js/art-files.js (the files that exist; cards without one keep the drawn art from js/art.js).
File names come from js/art-keys.js (artFileFor). Needs Pillow."""
import os, sys, glob, re, json
import numpy as np
from PIL import Image
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out, sm = os.path.join(root, 'assets/art/cards'), os.path.join(root, 'assets/art/cards/sm')
os.makedirs(sm, exist_ok=True)
for src in sorted(glob.glob(os.path.join(sys.argv[1], '*.png'))) if len(sys.argv) > 1 else []:
    name = os.path.basename(src)[:-4]
    if not re.fullmatch(r'[a-z0-9-]+', name): continue  # skips backups like sl-8.old123.png
    im = Image.open(src).convert('RGB')
    big = im.copy(); big.thumbnail((1200, 1200)); big.save(os.path.join(out, name + '.webp'), quality=80, method=6)
    small = im.copy(); small.thumbnail((440, 440)); small.save(os.path.join(sm, name + '.webp'), quality=76, method=6)
def find_stars(path, n=9):
    # Small bright points in dark sky: local maxima above 170 brightness, tiny (few bright pixels
    # around them) and with dark surroundings, so planets, satellites and Earth's limb are skipped.
    im = Image.open(path).convert('L'); im.thumbnail((600, 600))
    a = np.asarray(im).astype(float); h, w = a.shape; out = []
    ys, xs = np.where(a > 170)
    for y, x in zip(ys, xs):
        if y < 10 or x < 10 or y >= h - 10 or x >= w - 10: continue
        win = a[y - 3:y + 4, x - 3:x + 4]
        if a[y, x] < win.max() or (win > 140).sum() > 14: continue
        ring = np.concatenate([a[y - 9, x - 9:x + 10], a[y + 9, x - 9:x + 10], a[y - 9:y + 10, x - 9], a[y - 9:y + 10, x + 9]])
        if ring.mean() > 55 or ring.max() > 120: continue
        if any(abs(x - ox) < w * .06 and abs(y - oy) < h * .06 for ox, oy, _ in out): continue
        out.append((x, y, float(a[y, x])))
    out.sort(key=lambda t: -t[2])
    return {'r': round(w / h, 4), 's': [[round(x / w, 4), round(y / h, 4)] for x, y, _ in out[:n]]}

files = sorted(os.path.basename(f)[:-5] for f in glob.glob(os.path.join(out, '*.webp')))
stars = {f: find_stars(os.path.join(out, f + '.webp')) for f in files}
with open(os.path.join(root, 'js/art-files.js'), 'w') as f:
    f.write('// Generated by scripts/import-art.py: card illustrations that exist in assets/art/cards.\n')
    f.write('export const ART_FILES = new Set(' + repr(files).replace("'", '"') + ');\n')
    f.write('// Stars found in each picture\'s sky (x, y as fractions of the image; r = width / height), for the twinkle.\n')
    f.write('export const ART_STARS = ' + json.dumps(stars, separators=(',', ':')) + ';\n')
print(len(files), 'illustrations')
