#!/usr/bin/env python3
"""Import card illustrations: python3 scripts/import-art.py <folder of PNGs named by art file, e.g. sl-8.png, modern-satellite-2.png>

Writes assets/art/cards/<file>.webp (card art window), assets/art/cards/sm/<file>.webp (gallery tiles)
and js/art-files.js (the files that exist; cards without one keep the drawn art from js/art.js).
File names come from js/art-keys.js (artFileFor). Needs Pillow."""
import os, sys, glob, re
from PIL import Image
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out, sm = os.path.join(root, 'assets/art/cards'), os.path.join(root, 'assets/art/cards/sm')
os.makedirs(sm, exist_ok=True)
for src in sorted(glob.glob(os.path.join(sys.argv[1], '*.png'))) if len(sys.argv) > 1 else []:
    name = os.path.basename(src)[:-4]
    if not re.fullmatch(r'[a-z0-9-]+', name): continue  # skips backups like sl-8.old123.png
    im = Image.open(src).convert('RGB')
    big = im.copy(); big.thumbnail((1200, 1200)); big.save(os.path.join(out, name + '.webp'), quality=80, method=6)
    small = im.copy(); small.thumbnail((440, 440)); small.save(os.path.join(sm, name + '.webp'), quality=76, method=6)
files = sorted(os.path.basename(f)[:-5] for f in glob.glob(os.path.join(out, '*.webp')))
with open(os.path.join(root, 'js/art-files.js'), 'w') as f:
    f.write('// Generated by scripts/import-art.py: card illustrations that exist in assets/art/cards.\n')
    f.write('export const ART_FILES = new Set(' + repr(files).replace("'", '"') + ');\n')
print(len(files), 'illustrations')
